### ISSUE TITLE
Logo scene empty

### ISSUE THREAD

**Issue by CodeHelix** [fehaar/FFWD-Templates#1]
I am trying to go through the get started tutorial but when I open the Logo scene it only shows a blank screen and there are no assets. Not sure if it's something I did wrong on my end or if there is something missing the FFWD-Templates repository. 

Edit: I went ahead and tried using a small project already made to test FFWD out. What I did was create a package out of the FFWD-Templates and copied the files created from the ProjectInitializer into the my Unity project folder. I did this so I won't have so many projects in the original FFWD-Templates folders.

So far I have three lines of code from my scripts that are giving me errors which are:

Error   2   'PressPlay.FFWD.Components.Rigidbody' does not contain a definition for 'GetPointVelocity' and no extension method 'GetPointVelocity' accepting a first argument of type 'PressPlay.FFWD.Components.Rigidbody' could be found (are you missing a using directive or an assembly reference?) C:\Users\Public\Documents\Unity Projects\Test\Test.Scripts\AIscript.cs  124 26  Test.Scripts
Error   3   No overload for method 'AddForce' takes 3 arguments C:\Users\Public\Documents\Unity Projects\Test\Test.Scripts\AIscript.cs  125 3   Test.Scripts
Error   4   'PressPlay.FFWD.Material' does not contain a definition for 'SetTextureOffset' and no extension method 'SetTextureOffset' accepting a first argument of type 'PressPlay.FFWD.Material' could be found (are you missing a using directive or an assembly reference?) C:\Users\Public\Documents\Unity Projects\Test\Test.Scripts\AIscript.cs  213 38  Test.Scripts

I also get an error for the Windows and Windows Phone projects (haven't tested Xbox yet) which is:

Error   1   XML element "sharedMaterials" not found.    C:\Users\Public\Documents\Unity Projects\Test\Test.XmlContent\Scenes\scene.xml  548 12  Test.Win

I would post the block of XML code this is happening in but the site won't allow it to show correctly but it is for a particle.

**Comment by fehaar** [comment]
It is true that the logo scene is empty. I am waiting for the logo to get finished. It will just be a simple scene to test the setup.

It is totally all right to copy the files to another Unity project as well. he template is just there to help you get started. As long as you remember to set the correct path to your XNA project when you export - so the files get updated there, you should be all right.

The two errors you are getting are methods that have not yet been defined in the FFWD classes. I have added an implementation of them now. The one for material only really works if you try to set the offset for the MainTexture. At the monent the renderer will only use the offset/scale for statically batched things. It is one of the things I am working on at the moment. So it might now work properly - but now it should compile.

The Rigidbody method has also been implemented, and should work - if I understand the method correctly. I haven't tested it though.

The thing about the XML error is because the Exporter is out of date. I have redefined some of the values in the renderer, so the XML changed a bit. And I just forgot to update the Exporter.DLL. I have done that now, so if you update both the template and the FFWD project, and then reexport from Unity you should be fine.

If the XML error happens another time, you can open the PressPlay.FFWD.Exporter project and compile it yourself. That will make sure that the Exporter DLL is up to date for the next export.
